import { Inter, Rajdhani } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const rajdhani = Rajdhani({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-rajdhani",
  display: "swap",
});

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "AccessCard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${rajdhani.variable} antialiased h-screen bg-neutral-950 text-neutral-100`}
      >
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
